name: Mac Scalapack Test
on:
    workflow_dispatch:
    push:
    pull_request:
jobs:
    ci_test:
        strategy:
            matrix:
                os: [macos-latest]
                node: [Release, Debug]
        runs-on: ${{matrix.os}}
        steps:
            - name: Install Libraries
              working-directory: ${{runner.workspace}}
              run: brew install scalapack
            - name: Git checkout
              uses: actions/checkout@v1
            - name: Makedir
              working-directory: ${{runner.workspace}}/asgard
              run: cmake -E make_directory build
            - name: Configure
              working-directory: ${{runner.workspace}}/asgard/build
              run: cmake -DCMAKE_BUILD_TYPE=${{matrix.node}} -DASGARD_USE_OPENMP=OFF -DASGARD_USE_MPI=ON -DASGARD_USE_SCALAPACK=ON -DCMAKE_Fortran_COMPILER=/usr/local/opt/gfortran ../
            - name: Show Cmake Log
              if: failure()
              working-directory: ${{runner.workspace}}/asgard/build/CMakeFiles
              run: ls /usr/local/opt/
                   cat CMakeError.log
            - name: Build
              working-directory: ${{runner.workspace}}/asgard/build
              run: make VERBOSE=1
            - name: Test
              working-directory: ${{runner.workspace}}/asgard/build
              run: make test
            - name: Show Log
              if: failure()
              working-directory: ${{runner.workspace}}/asgard/build/Testing/Temporary
              run: cat LastTest.log
